# Generated by Django 5.1 on 2024-09-20 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='cargado_en',
        ),
    ]
