# Generated by Django 5.1 on 2024-09-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default='1955-01-01', verbose_name='Fecha de nacimiento'),
        ),
    ]
